name: macOS Custom Godot Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: Build Godot macOS Editor
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install scons pkg-config
          brew install yasm
          brew install python@3.11
          brew install llvm
          echo "Dependencies installed."

      - name: Set up Python (for SCons)
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jinja2

      - name: Show system info
        run: |
          uname -a
          python3 --version
          scons --version

      - name: Build Godot (Release)
        run: |
          # For Apple Silicon (M1/M2/M3)
          scons platform=macos arch=arm64 target=release_debug use_llvm=yes -j$(sysctl -n hw.logicalcpu)

          # If you want Intel build, comment above and uncomment below:
          # scons platform=macos arch=x86_64 target=release_debug use_llvm=yes -j$(sysctl -n hw.logicalcpu)

      - name: Package editor .app bundle
        run: |
          mkdir -p build_out
          mv bin/godot.macos.editor.arm64 build_out/Godot.app
          cd build_out
          zip -r Godot-macos-custom.zip Godot.app
          cd ..

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot-macos-custom
          path: build_out/Godot-macos-custom.zip